-- MySQL Script generated by MySQL Workbench
-- Tue Dec  2 16:43:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ClinicaMedica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ClinicaMedica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ClinicaMedica` DEFAULT CHARACTER SET utf8 ;
USE `ClinicaMedica` ;

-- -----------------------------------------------------
-- Table `ClinicaMedica`.`Consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaMedica`.`Consultorio` (
  `numConsultorio` INT UNSIGNED NOT NULL,
  `corredor` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numConsultorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaMedica`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaMedica`.`Medico` (
  `cpfMedico` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `Consultorio_numConsultorio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cpfMedico`),
  UNIQUE INDEX `cpfMedico_UNIQUE` (`cpfMedico` ASC),
  INDEX `fk_Medico_Consultorio1_idx` (`Consultorio_numConsultorio` ASC),
  CONSTRAINT `fk_Medico_Consultorio1`
    FOREIGN KEY (`Consultorio_numConsultorio`)
    REFERENCES `ClinicaMedica`.`Consultorio` (`numConsultorio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaMedica`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaMedica`.`Paciente` (
  `cpfPaciente` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `Medico_cpfMedico` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cpfPaciente`),
  UNIQUE INDEX `cpfPaciente_UNIQUE` (`cpfPaciente` ASC),
  INDEX `fk_Paciente_Medico1_idx` (`Medico_cpfMedico` ASC),
  CONSTRAINT `fk_Paciente_Medico1`
    FOREIGN KEY (`Medico_cpfMedico`)
    REFERENCES `ClinicaMedica`.`Medico` (`cpfMedico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaMedica`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaMedica`.`Consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `Medico_cpfMedico` VARCHAR(11) NOT NULL,
  `Paciente_cpfPaciente` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idConsulta`),
  INDEX `fk_Consulta_Medico_idx` (`Medico_cpfMedico` ASC),
  INDEX `fk_Consulta_Paciente1_idx` (`Paciente_cpfPaciente` ASC),
  CONSTRAINT `fk_Consulta_Medico`
    FOREIGN KEY (`Medico_cpfMedico`)
    REFERENCES `ClinicaMedica`.`Medico` (`cpfMedico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`Paciente_cpfPaciente`)
    REFERENCES `ClinicaMedica`.`Paciente` (`cpfPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaMedica`.`Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaMedica`.`Exame` (
  `idExame` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`idExame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaMedica`.`Medico_Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaMedica`.`Medico_Exame` (
  `Medico_cpfMedico` VARCHAR(11) NOT NULL,
  `Exame_idExame` INT NOT NULL,
  PRIMARY KEY (`Medico_cpfMedico`, `Exame_idExame`),
  INDEX `fk_Medico_has_Exame_Exame1_idx` (`Exame_idExame` ASC),
  INDEX `fk_Medico_has_Exame_Medico1_idx` (`Medico_cpfMedico` ASC),
  CONSTRAINT `fk_Medico_has_Exame_Medico1`
    FOREIGN KEY (`Medico_cpfMedico`)
    REFERENCES `ClinicaMedica`.`Medico` (`cpfMedico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Medico_has_Exame_Exame1`
    FOREIGN KEY (`Exame_idExame`)
    REFERENCES `ClinicaMedica`.`Exame` (`idExame`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaMedica`.`Paciente_Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaMedica`.`Paciente_Exame` (
  `Paciente_cpfPaciente` VARCHAR(11) NOT NULL,
  `Exame_idExame` INT NOT NULL,
  PRIMARY KEY (`Paciente_cpfPaciente`, `Exame_idExame`),
  INDEX `fk_Paciente_has_Exame_Exame1_idx` (`Exame_idExame` ASC),
  INDEX `fk_Paciente_has_Exame_Paciente1_idx` (`Paciente_cpfPaciente` ASC),
  CONSTRAINT `fk_Paciente_has_Exame_Paciente1`
    FOREIGN KEY (`Paciente_cpfPaciente`)
    REFERENCES `ClinicaMedica`.`Paciente` (`cpfPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Paciente_has_Exame_Exame1`
    FOREIGN KEY (`Exame_idExame`)
    REFERENCES `ClinicaMedica`.`Exame` (`idExame`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
